### PR TITLE
Clearing global vars, and some bugfix

### PR DESCRIPTION
**Pull request by M5Mathieu**
Error fixes, as well some minor changes. This fixes issues with tryin…g to restart appweb (esp, ejs not tested). Without this, appweb crashes during to restart due to the global variables not being reset to 0 after terminating appweb

### CODE REVIEW

**Comment by embedthis** [comment]
Thank you. We'll pull this apart into separate issues + fixes. Thank you for taking the time with this.

In the future, you can make separate issues with associated pull requests and then we can take the patches as you make them.

Thanks

**Comment by embedthis** [comment]
One of the changes may have a problem.

In httpLogin: changing httpCreateSession with httpGetSession won't work for everyone as you cannot reuse an existing session with old login data.

And where did you invoke maConfigParsingDestroy from? I did not see a call to that.

You said you were trying to restart appweb. How were you doing the restart?

**Comment by M5Mathieu** [comment]
I admit that httpCreateSession I a bit specific and might not be the best way. 
Appweb is intergrated in our software, and our software allows session comming from multiple sources, for exemple CLI, so it has it's internal session managing. We use the appweb session session has  a unique identifier allowing to share the same session state between appweb and our software. In other words, we have a custom authStore, and we create the session at that moment. If it would not work with everyone, please discard.

True, I forgot to add in maConfigParsingDestroy in our appweb exemple, my bad. We added in our software... We call it after mprDestroy. Should probably be doing it within mprDestroy.

**Comment by M5Mathieu** [comment]
For references, I added a sample allowing to restart appweb, from the web (feels wierd, but has a sample, it's does the job)

**Comment by embedthis** [comment]
Thanks for the update. We'll review.

A cleaner way for calling destroy may be via mprAddTerminator. This adds a function to run when mprDestroy is called or the application is exited.

**Comment by M5Mathieu** [comment]
I just reverted to httpCreateSession, even if that mean we will have to maintain this difference.

Now using a terminator, it's cleaner that way, thanks!

**Pull request closed without merging**
